version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_data:/code/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:15.0-alpine
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myDB

    

volumes: 
  postgres_data:
  media_data:
